server:
  port: 9000
#配置eureka server
eureka:
  instance:
    hostname: localhost
  client:
#    register-with-eureka: false  #是否讲自己注册到注册中心
#    fetch-registry: false #是否从eureka 中获取注册信息
    registerWithEureka=false
    fetchRegistry=false
    serviceUrl: #配置暴露给eureka 的请求地址
#     defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone=http://localhost:9000/eureka/